title: Ahmad Amine
position: Ph.D. student in Electrical and Systems Engineering
affiliation: University of Pennsylvania
affiliation_link: https://www.upenn.edu/
description: Ahmad Amine researches data-driven safe iterative control, model predictive control, and online system identification at the University of Pennsylvania.
url: https://ahmadamine998.github.io
baseurl: ""
lang: en-US
google_scholar: https://scholar.google.com/citations?user=TvKVG9AAAAAJ&hl=en
cv_link: /assets/files/curriculum_vitae.pdf
github_link: https://github.com/AhmadAmine998
linkedin: https://www.linkedin.com/in/ahmadamine/
avatar: /assets/img/avatar.png
favicon: /assets/img/favicon.png
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
